### ISSUE TITLE
Using 'advimage' setting with big images generates error

### ISSUE THREAD

**Issue by joeke** [donShakespeare/tinymce_wrapper#7]
When using the 'advimage' setting, and rotate a large-ish image (1MB+) inside the content field, the rotated image gets saved as a blob, which results in an image src with a blob of about 2.000.000 character which when saving throws an error in MODX, due to the content field being too large.
Do you know of any solution for this?

**Comment by donShakespeare** [comment]
@joeke `advimage` or `imagetools` ?
TinymceWrapper 3.0 comes with *rapidImage* plugin that takes care of all of that.

You are having the issues because TinyMCE does not (nor cannot) handle that your request by default.

Once an image is manipulated (non-superficially), it becomes a raw data/blob. You need a server-side script to take care of that business. See the image demo on Slack.

Cheers
